-- Add lc_number column to contract_drafts table
-- LC Number is the unique identifier generated by ECTA when registering a contract

ALTER TABLE contract_drafts 
ADD COLUMN IF NOT EXISTS lc_number VARCHAR(50) UNIQUE;

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_contract_drafts_lc_number ON contract_drafts(lc_number);

-- Add registered_at and registered_by columns if they don't exist
ALTER TABLE contract_drafts 
ADD COLUMN IF NOT EXISTS registered_at TIMESTAMP;

ALTER TABLE contract_drafts 
ADD COLUMN IF NOT EXISTS registered_by VARCHAR(255);

ALTER TABLE contract_drafts 
ADD COLUMN IF NOT EXISTS registration_notes TEXT;

COMMENT ON COLUMN contract_drafts.lc_number IS 'Letter of Credit number generated by ECTA upon registration';
COMMENT ON COLUMN contract_drafts.registered_at IS 'Timestamp when contract was registered by ECTA';
COMMENT ON COLUMN contract_drafts.registered_by IS 'ECTA officer who registered the contract';
COMMENT ON COLUMN contract_drafts.registration_notes IS 'Notes added during registration';
