-- Simple Marketplace Seed Data
-- Matches actual table structure

BEGIN;

-- Insert buyers into buyer_registry
INSERT INTO buyer_registry (
    company_name,
    country,
    registration_number,
    email,
    phone,
    verification_status,
    risk_level,
    reputation_score,
    total_contracts,
    successful_contracts
) VALUES 
('Global Coffee Importers Ltd', 'United States', 'US-GCI-2024-001', 'procurement@globalcoffee.com', '+1-212-555-0100', 'VERIFIED', 'LOW', 4.8, 45, 43),
('European Coffee Trading GmbH', 'Germany', 'DE-ECT-2024-002', 'buyers@eurocoffee.de', '+49-40-555-0200', 'VERIFIED', 'LOW', 4.6, 32, 30),
('Asian Coffee Distributors', 'Japan', 'JP-ACD-2024-003', 'import@asiancoffee.jp', '+81-3-555-0300', 'VERIFIED', 'MEDIUM', 4.5, 28, 26),
('Middle East Coffee House', 'United Arab Emirates', 'AE-MECH-2024-004', 'trading@mecoffee.ae', '+971-4-555-0400', 'VERIFIED', 'LOW', 4.7, 38, 36),
('Specialty Coffee Roasters UK', 'United Kingdom', 'UK-SCR-2024-005', 'sourcing@specialtyroasters.co.uk', '+44-20-555-0500', 'VERIFIED', 'LOW', 4.9, 52, 51)
ON CONFLICT (registration_number, country) DO NOTHING;

-- Insert buyer opportunities
INSERT INTO buyer_opportunities (
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES 
(
    (SELECT buyer_id FROM buyer_registry WHERE registration_number = 'US-GCI-2024-001' LIMIT 1),
    'Premium Arabica Coffee - Long-term Supply',
    'Seeking reliable Ethiopian exporter for premium Arabica coffee. Looking for consistent quality and long-term partnership. Preference for Yirgacheffe and Sidamo regions.',
    'ARABICA',
    ARRAY['Yirgacheffe', 'Sidamo', 'Guji'],
    'Grade 1',
    1000,
    2000,
    'MONTHLY',
    24,
    ARRAY['LC_AT_SIGHT', 'LC_DEFERRED'],
    ARRAY['FOB', 'CFR'],
    4.50,
    5.50,
    'USD',
    ARRAY['Fair Trade', 'Organic', 'Rainforest Alliance'],
    'United States',
    'Port of New York',
    NOW() + INTERVAL '90 days',
    'OPEN'
),
(
    (SELECT buyer_id FROM buyer_registry WHERE registration_number = 'DE-ECT-2024-002' LIMIT 1),
    'Specialty Grade Ethiopian Coffee',
    'European specialty coffee roaster seeking high-quality Ethiopian beans. Focus on unique flavor profiles and traceability.',
    'SPECIALTY',
    ARRAY['Yirgacheffe', 'Harrar', 'Limu'],
    'Grade 1',
    500,
    1000,
    'QUARTERLY',
    12,
    ARRAY['LC_AT_SIGHT', 'TT_ADVANCE'],
    ARRAY['FOB', 'CIF'],
    6.00,
    8.00,
    'EUR',
    ARRAY['Organic', 'Direct Trade'],
    'Germany',
    'Port of Hamburg',
    NOW() + INTERVAL '60 days',
    'OPEN'
),
(
    (SELECT buyer_id FROM buyer_registry WHERE registration_number = 'JP-ACD-2024-003' LIMIT 1),
    'Certified Organic Ethiopian Coffee',
    'Growing demand for organic Ethiopian coffee in Japanese market. Seeking certified organic beans with full traceability.',
    'ORGANIC',
    ARRAY['Sidamo', 'Yirgacheffe'],
    'Grade 1',
    300,
    600,
    'MONTHLY',
    18,
    ARRAY['LC_AT_SIGHT'],
    ARRAY['CIF', 'CFR'],
    5.50,
    7.00,
    'USD',
    ARRAY['Organic', 'JAS Organic'],
    'Japan',
    'Port of Tokyo',
    NOW() + INTERVAL '45 days',
    'OPEN'
),
(
    (SELECT buyer_id FROM buyer_registry WHERE registration_number = 'AE-MECH-2024-004' LIMIT 1),
    'High-Volume Arabica for Retail Market',
    'Established coffee chain seeking consistent supply of quality Arabica for retail operations across UAE.',
    'ARABICA',
    ARRAY['Sidamo', 'Jimma', 'Limu'],
    'Grade 2',
    1500,
    3000,
    'MONTHLY',
    36,
    ARRAY['LC_DEFERRED', 'LC_AT_SIGHT'],
    ARRAY['FOB', 'CFR'],
    3.80,
    4.80,
    'USD',
    ARRAY[]::text[],
    'United Arab Emirates',
    'Port of Jebel Ali',
    NOW() + INTERVAL '120 days',
    'OPEN'
),
(
    (SELECT buyer_id FROM buyer_registry WHERE registration_number = 'UK-SCR-2024-005' LIMIT 1),
    'Single-Origin Ethiopian Microlots',
    'Award-winning UK roaster seeking exceptional Ethiopian microlots. Focus on unique terroir and farmer stories.',
    'SPECIALTY',
    ARRAY['Yirgacheffe', 'Guji', 'Harrar'],
    'Grade 1',
    200,
    500,
    'QUARTERLY',
    12,
    ARRAY['TT_ADVANCE', 'LC_AT_SIGHT'],
    ARRAY['FOB', 'CIF'],
    8.00,
    12.00,
    'GBP',
    ARRAY['Direct Trade', 'Organic', 'Fair Trade'],
    'United Kingdom',
    'Port of Felixstowe',
    NOW() + INTERVAL '75 days',
    'OPEN'
),
(
    (SELECT buyer_id FROM buyer_registry WHERE registration_number = 'US-GCI-2024-001' LIMIT 1),
    'Robusta Coffee for Espresso Blends',
    'Seeking quality Robusta beans for espresso blend component. Consistent quality and competitive pricing essential.',
    'ROBUSTA',
    ARRAY['Jimma', 'Bebeka'],
    'Grade 2',
    800,
    1500,
    'MONTHLY',
    24,
    ARRAY['LC_AT_SIGHT'],
    ARRAY['FOB'],
    2.50,
    3.50,
    'USD',
    ARRAY[]::text[],
    'United States',
    'Port of New York',
    NOW() + INTERVAL '90 days',
    'OPEN'
);

COMMIT;
