-- Seed Marketplace Data
-- Sample buyer opportunities for testing

-- First, ensure we have some buyers in the buyer_registry
INSERT INTO buyer_registry (
    buyer_id,
    company_name,
    country,
    city,
    contact_email,
    contact_phone,
    business_registration_number,
    verification_status,
    risk_level,
    reputation_score,
    total_contracts,
    successful_contracts
) VALUES 
(
    gen_random_uuid(),
    'Global Coffee Importers Ltd',
    'United States',
    'New York',
    'procurement@globalcoffee.com',
    '+1-212-555-0100',
    'US-GCI-2024-001',
    'VERIFIED',
    'LOW',
    4.8,
    45,
    43
),
(
    gen_random_uuid(),
    'European Coffee Trading GmbH',
    'Germany',
    'Hamburg',
    'buyers@eurocoffee.de',
    '+49-40-555-0200',
    'DE-ECT-2024-002',
    'VERIFIED',
    'LOW',
    4.6,
    32,
    30
),
(
    gen_random_uuid(),
    'Asian Coffee Distributors',
    'Japan',
    'Tokyo',
    'import@asiancoffee.jp',
    '+81-3-555-0300',
    'JP-ACD-2024-003',
    'VERIFIED',
    'MEDIUM',
    4.5,
    28,
    26
),
(
    gen_random_uuid(),
    'Middle East Coffee House',
    'United Arab Emirates',
    'Dubai',
    'trading@mecoffee.ae',
    '+971-4-555-0400',
    'AE-MECH-2024-004',
    'VERIFIED',
    'LOW',
    4.7,
    38,
    36
),
(
    gen_random_uuid(),
    'Specialty Coffee Roasters UK',
    'United Kingdom',
    'London',
    'sourcing@specialtyroasters.co.uk',
    '+44-20-555-0500',
    'UK-SCR-2024-005',
    'VERIFIED',
    'LOW',
    4.9,
    52,
    51
)
ON CONFLICT (business_registration_number) DO NOTHING;

-- Now create buyer opportunities
-- Opportunity 1: High-volume Arabica for US market
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'Global Coffee Importers Ltd' LIMIT 1),
    'Premium Arabica Coffee - Long-term Supply',
    'Seeking reliable Ethiopian exporter for premium Arabica coffee. Looking for consistent quality and long-term partnership. Preference for Yirgacheffe and Sidamo regions.',
    'ARABICA',
    ARRAY['Yirgacheffe', 'Sidamo', 'Guji'],
    'Grade 1',
    1000,
    2000,
    'MONTHLY',
    24,
    ARRAY['LC_AT_SIGHT', 'LC_DEFERRED'],
    ARRAY['FOB', 'CFR'],
    4.50,
    5.50,
    'USD',
    ARRAY['Fair Trade', 'Organic', 'Rainforest Alliance'],
    'United States',
    'Port of New York',
    NOW() + INTERVAL '90 days',
    'OPEN'
);

-- Opportunity 2: Specialty coffee for European market
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'European Coffee Trading GmbH' LIMIT 1),
    'Specialty Grade Ethiopian Coffee',
    'European specialty coffee roaster seeking high-quality Ethiopian beans. Focus on unique flavor profiles and traceability. Small to medium volumes with potential for growth.',
    'SPECIALTY',
    ARRAY['Yirgacheffe', 'Harrar', 'Limu'],
    'Grade 1',
    500,
    1000,
    'QUARTERLY',
    12,
    ARRAY['LC_AT_SIGHT', 'TT_ADVANCE'],
    ARRAY['FOB', 'CIF'],
    6.00,
    8.00,
    'EUR',
    ARRAY['Organic', 'Direct Trade'],
    'Germany',
    'Port of Hamburg',
    NOW() + INTERVAL '60 days',
    'OPEN'
);

-- Opportunity 3: Organic coffee for Asian market
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'Asian Coffee Distributors' LIMIT 1),
    'Certified Organic Ethiopian Coffee',
    'Growing demand for organic Ethiopian coffee in Japanese market. Seeking certified organic beans with full traceability. Preference for washed process.',
    'ORGANIC',
    ARRAY['Sidamo', 'Yirgacheffe'],
    'Grade 1',
    300,
    600,
    'BIMONTHLY',
    18,
    ARRAY['LC_AT_SIGHT'],
    ARRAY['CIF', 'CFR'],
    5.50,
    7.00,
    'USD',
    ARRAY['Organic', 'JAS Organic'],
    'Japan',
    'Port of Tokyo',
    NOW() + INTERVAL '45 days',
    'OPEN'
);

-- Opportunity 4: Commercial grade for Middle East
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'Middle East Coffee House' LIMIT 1),
    'High-Volume Arabica for Retail Market',
    'Established coffee chain seeking consistent supply of quality Arabica for retail operations across UAE. High volume, competitive pricing, reliable delivery schedule required.',
    'ARABICA',
    ARRAY['Sidamo', 'Jimma', 'Limu'],
    'Grade 2',
    1500,
    3000,
    'MONTHLY',
    36,
    ARRAY['LC_DEFERRED', 'LC_AT_SIGHT'],
    ARRAY['FOB', 'CFR'],
    3.80,
    4.80,
    'USD',
    ARRAY[],
    'United Arab Emirates',
    'Port of Jebel Ali',
    NOW() + INTERVAL '120 days',
    'OPEN'
);

-- Opportunity 5: Premium specialty for UK market
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'Specialty Coffee Roasters UK' LIMIT 1),
    'Single-Origin Ethiopian Microlots',
    'Award-winning UK roaster seeking exceptional Ethiopian microlots. Focus on unique terroir, processing methods, and farmer stories. Premium pricing for exceptional quality.',
    'SPECIALTY',
    ARRAY['Yirgacheffe', 'Guji', 'Harrar'],
    'Grade 1',
    200,
    500,
    'QUARTERLY',
    12,
    ARRAY['TT_ADVANCE', 'LC_AT_SIGHT'],
    ARRAY['FOB', 'CIF'],
    8.00,
    12.00,
    'GBP',
    ARRAY['Direct Trade', 'Organic', 'Fair Trade'],
    'United Kingdom',
    'Port of Felixstowe',
    NOW() + INTERVAL '75 days',
    'OPEN'
);

-- Opportunity 6: Robusta blend component
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'Global Coffee Importers Ltd' LIMIT 1),
    'Robusta Coffee for Espresso Blends',
    'Seeking quality Robusta beans for espresso blend component. Consistent quality and competitive pricing essential. Long-term partnership opportunity.',
    'ROBUSTA',
    ARRAY['Jimma', 'Bebeka'],
    'Grade 2',
    800,
    1500,
    'MONTHLY',
    24,
    ARRAY['LC_AT_SIGHT'],
    ARRAY['FOB'],
    2.50,
    3.50,
    'USD',
    ARRAY[],
    'United States',
    'Port of New York',
    NOW() + INTERVAL '90 days',
    'OPEN'
);

-- Add some closed/expired opportunities for testing filters
INSERT INTO buyer_opportunities (
    opportunity_id,
    buyer_id,
    title,
    description,
    coffee_type,
    origin_preferences,
    quality_grade_min,
    quantity_min,
    quantity_max,
    frequency,
    contract_duration_months,
    preferred_payment_terms,
    preferred_incoterms,
    target_price_min,
    target_price_max,
    currency,
    certifications_required,
    destination_country,
    destination_port,
    valid_until,
    status
) VALUES (
    gen_random_uuid(),
    (SELECT buyer_id FROM buyer_registry WHERE company_name = 'European Coffee Trading GmbH' LIMIT 1),
    'Expired Opportunity - Test',
    'This opportunity has expired and should not appear in active listings.',
    'ARABICA',
    ARRAY['Yirgacheffe'],
    'Grade 1',
    500,
    1000,
    'MONTHLY',
    12,
    ARRAY['LC_AT_SIGHT'],
    ARRAY['FOB'],
    5.00,
    6.00,
    'EUR',
    ARRAY['Organic'],
    'Germany',
    'Port of Hamburg',
    NOW() - INTERVAL '10 days',
    'OPEN'
);

COMMIT;
