/**
 * Unified Status Constants
 * Single source of truth for all export statuses across the system
 * Used by: Frontend, Backend API, Smart Contract, Database
 */

// Export Status - Unified across all layers
export const EXPORT_STATUS = {
  // Initial State
  DRAFT: 'DRAFT',

  // ECX Phase
  ECX_PENDING: 'ECX_PENDING',
  ECX_VERIFIED: 'ECX_VERIFIED',
  ECX_REJECTED: 'ECX_REJECTED',

  // ECTA Phase - License
  ECTA_LICENSE_PENDING: 'ECTA_LICENSE_PENDING',
  ECTA_LICENSE_APPROVED: 'ECTA_LICENSE_APPROVED',
  ECTA_LICENSE_REJECTED: 'ECTA_LICENSE_REJECTED',

  // ECTA Phase - Quality
  ECTA_QUALITY_PENDING: 'ECTA_QUALITY_PENDING',
  ECTA_QUALITY_APPROVED: 'ECTA_QUALITY_APPROVED',
  ECTA_QUALITY_REJECTED: 'ECTA_QUALITY_REJECTED',

  // ECTA Phase - Contract
  ECTA_CONTRACT_PENDING: 'ECTA_CONTRACT_PENDING',
  ECTA_CONTRACT_APPROVED: 'ECTA_CONTRACT_APPROVED',
  ECTA_CONTRACT_REJECTED: 'ECTA_CONTRACT_REJECTED',

  // Commercial Bank Phase
  BANK_DOCUMENT_PENDING: 'BANK_DOCUMENT_PENDING',
  BANK_DOCUMENT_VERIFIED: 'BANK_DOCUMENT_VERIFIED',
  BANK_DOCUMENT_REJECTED: 'BANK_DOCUMENT_REJECTED',

  // NBE Phase
  FX_APPLICATION_PENDING: 'FX_APPLICATION_PENDING',
  FX_APPROVED: 'FX_APPROVED',
  FX_REJECTED: 'FX_REJECTED',

  // Customs Phase
  CUSTOMS_PENDING: 'CUSTOMS_PENDING',
  CUSTOMS_CLEARED: 'CUSTOMS_CLEARED',
  CUSTOMS_REJECTED: 'CUSTOMS_REJECTED',

  // Shipment Phase
  READY_FOR_SHIPMENT: 'READY_FOR_SHIPMENT',
  SHIPMENT_SCHEDULED: 'SHIPMENT_SCHEDULED',
  SHIPPED: 'SHIPPED',

  // Destination Phase
  ARRIVED: 'ARRIVED',
  IMPORT_CUSTOMS_PENDING: 'IMPORT_CUSTOMS_PENDING',
  IMPORT_CUSTOMS_CLEARED: 'IMPORT_CUSTOMS_CLEARED',
  IMPORT_CUSTOMS_REJECTED: 'IMPORT_CUSTOMS_REJECTED',
  DELIVERED: 'DELIVERED',

  // Payment Phase
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  FX_REPATRIATION_PENDING: 'FX_REPATRIATION_PENDING',
  FX_REPATRIATED: 'FX_REPATRIATED',

  // Terminal States
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

// Status type
export type ExportStatus = (typeof EXPORT_STATUS)[keyof typeof EXPORT_STATUS];

// Status groups for filtering
export const STATUS_GROUPS = {
  REJECTED: [
    EXPORT_STATUS.ECX_REJECTED,
    EXPORT_STATUS.ECTA_LICENSE_REJECTED,
    EXPORT_STATUS.ECTA_QUALITY_REJECTED,
    EXPORT_STATUS.ECTA_CONTRACT_REJECTED,
    EXPORT_STATUS.BANK_DOCUMENT_REJECTED,
    EXPORT_STATUS.FX_REJECTED,
    EXPORT_STATUS.CUSTOMS_REJECTED,
    EXPORT_STATUS.IMPORT_CUSTOMS_REJECTED,
  ],
  PENDING: [
    EXPORT_STATUS.ECX_PENDING,
    EXPORT_STATUS.ECTA_LICENSE_PENDING,
    EXPORT_STATUS.ECTA_QUALITY_PENDING,
    EXPORT_STATUS.ECTA_CONTRACT_PENDING,
    EXPORT_STATUS.BANK_DOCUMENT_PENDING,
    EXPORT_STATUS.FX_APPLICATION_PENDING,
    EXPORT_STATUS.CUSTOMS_PENDING,
    EXPORT_STATUS.IMPORT_CUSTOMS_PENDING,
    EXPORT_STATUS.PAYMENT_PENDING,
    EXPORT_STATUS.FX_REPATRIATION_PENDING,
  ],
  APPROVED: [
    EXPORT_STATUS.ECX_VERIFIED,
    EXPORT_STATUS.ECTA_LICENSE_APPROVED,
    EXPORT_STATUS.ECTA_QUALITY_APPROVED,
    EXPORT_STATUS.ECTA_CONTRACT_APPROVED,
    EXPORT_STATUS.BANK_DOCUMENT_VERIFIED,
    EXPORT_STATUS.FX_APPROVED,
    EXPORT_STATUS.CUSTOMS_CLEARED,
    EXPORT_STATUS.IMPORT_CUSTOMS_CLEARED,
    EXPORT_STATUS.PAYMENT_RECEIVED,
    EXPORT_STATUS.FX_REPATRIATED,
  ],
  TERMINAL: [EXPORT_STATUS.COMPLETED, EXPORT_STATUS.CANCELLED],
};

// Status labels for UI
export const STATUS_LABELS: Record<ExportStatus, string> = {
  [EXPORT_STATUS.DRAFT]: 'Draft',
  [EXPORT_STATUS.ECX_PENDING]: 'Pending ECX Verification',
  [EXPORT_STATUS.ECX_VERIFIED]: 'ECX Verified',
  [EXPORT_STATUS.ECX_REJECTED]: 'ECX Rejected',
  [EXPORT_STATUS.ECTA_LICENSE_PENDING]: 'Pending License Approval',
  [EXPORT_STATUS.ECTA_LICENSE_APPROVED]: 'License Approved',
  [EXPORT_STATUS.ECTA_LICENSE_REJECTED]: 'License Rejected',
  [EXPORT_STATUS.ECTA_QUALITY_PENDING]: 'Pending Quality Certification',
  [EXPORT_STATUS.ECTA_QUALITY_APPROVED]: 'Quality Certified',
  [EXPORT_STATUS.ECTA_QUALITY_REJECTED]: 'Quality Rejected',
  [EXPORT_STATUS.ECTA_CONTRACT_PENDING]: 'Pending Contract Approval',
  [EXPORT_STATUS.ECTA_CONTRACT_APPROVED]: 'Contract Approved',
  [EXPORT_STATUS.ECTA_CONTRACT_REJECTED]: 'Contract Rejected',
  [EXPORT_STATUS.BANK_DOCUMENT_PENDING]: 'Pending Document Verification',
  [EXPORT_STATUS.BANK_DOCUMENT_VERIFIED]: 'Documents Verified',
  [EXPORT_STATUS.BANK_DOCUMENT_REJECTED]: 'Documents Rejected',
  [EXPORT_STATUS.FX_APPLICATION_PENDING]: 'Pending FX Approval',
  [EXPORT_STATUS.FX_APPROVED]: 'FX Approved',
  [EXPORT_STATUS.FX_REJECTED]: 'FX Rejected',
  [EXPORT_STATUS.CUSTOMS_PENDING]: 'Pending Customs Clearance',
  [EXPORT_STATUS.CUSTOMS_CLEARED]: 'Customs Cleared',
  [EXPORT_STATUS.CUSTOMS_REJECTED]: 'Customs Rejected',
  [EXPORT_STATUS.READY_FOR_SHIPMENT]: 'Ready for Shipment',
  [EXPORT_STATUS.SHIPMENT_SCHEDULED]: 'Shipment Scheduled',
  [EXPORT_STATUS.SHIPPED]: 'Shipped',
  [EXPORT_STATUS.ARRIVED]: 'Arrived at Destination',
  [EXPORT_STATUS.IMPORT_CUSTOMS_PENDING]: 'Pending Import Customs',
  [EXPORT_STATUS.IMPORT_CUSTOMS_CLEARED]: 'Import Customs Cleared',
  [EXPORT_STATUS.IMPORT_CUSTOMS_REJECTED]: 'Import Customs Rejected',
  [EXPORT_STATUS.DELIVERED]: 'Delivered',
  [EXPORT_STATUS.PAYMENT_PENDING]: 'Pending Payment',
  [EXPORT_STATUS.PAYMENT_RECEIVED]: 'Payment Received',
  [EXPORT_STATUS.FX_REPATRIATION_PENDING]: 'Pending FX Repatriation',
  [EXPORT_STATUS.FX_REPATRIATED]: 'FX Repatriated',
  [EXPORT_STATUS.COMPLETED]: 'Completed',
  [EXPORT_STATUS.CANCELLED]: 'Cancelled',
};

// Status colors for UI
export const STATUS_COLORS: Record<ExportStatus, string> = {
  [EXPORT_STATUS.DRAFT]: '#9E9E9E',
  [EXPORT_STATUS.ECX_PENDING]: '#FF9800',
  [EXPORT_STATUS.ECX_VERIFIED]: '#4CAF50',
  [EXPORT_STATUS.ECX_REJECTED]: '#F44336',
  [EXPORT_STATUS.ECTA_LICENSE_PENDING]: '#FF9800',
  [EXPORT_STATUS.ECTA_LICENSE_APPROVED]: '#4CAF50',
  [EXPORT_STATUS.ECTA_LICENSE_REJECTED]: '#F44336',
  [EXPORT_STATUS.ECTA_QUALITY_PENDING]: '#FF9800',
  [EXPORT_STATUS.ECTA_QUALITY_APPROVED]: '#4CAF50',
  [EXPORT_STATUS.ECTA_QUALITY_REJECTED]: '#F44336',
  [EXPORT_STATUS.ECTA_CONTRACT_PENDING]: '#FF9800',
  [EXPORT_STATUS.ECTA_CONTRACT_APPROVED]: '#4CAF50',
  [EXPORT_STATUS.ECTA_CONTRACT_REJECTED]: '#F44336',
  [EXPORT_STATUS.BANK_DOCUMENT_PENDING]: '#FF9800',
  [EXPORT_STATUS.BANK_DOCUMENT_VERIFIED]: '#4CAF50',
  [EXPORT_STATUS.BANK_DOCUMENT_REJECTED]: '#F44336',
  [EXPORT_STATUS.FX_APPLICATION_PENDING]: '#FF9800',
  [EXPORT_STATUS.FX_APPROVED]: '#4CAF50',
  [EXPORT_STATUS.FX_REJECTED]: '#F44336',
  [EXPORT_STATUS.CUSTOMS_PENDING]: '#FF9800',
  [EXPORT_STATUS.CUSTOMS_CLEARED]: '#4CAF50',
  [EXPORT_STATUS.CUSTOMS_REJECTED]: '#F44336',
  [EXPORT_STATUS.READY_FOR_SHIPMENT]: '#2196F3',
  [EXPORT_STATUS.SHIPMENT_SCHEDULED]: '#2196F3',
  [EXPORT_STATUS.SHIPPED]: '#2196F3',
  [EXPORT_STATUS.ARRIVED]: '#2196F3',
  [EXPORT_STATUS.IMPORT_CUSTOMS_PENDING]: '#FF9800',
  [EXPORT_STATUS.IMPORT_CUSTOMS_CLEARED]: '#4CAF50',
  [EXPORT_STATUS.IMPORT_CUSTOMS_REJECTED]: '#F44336',
  [EXPORT_STATUS.DELIVERED]: '#4CAF50',
  [EXPORT_STATUS.PAYMENT_PENDING]: '#FF9800',
  [EXPORT_STATUS.PAYMENT_RECEIVED]: '#4CAF50',
  [EXPORT_STATUS.FX_REPATRIATION_PENDING]: '#FF9800',
  [EXPORT_STATUS.FX_REPATRIATED]: '#4CAF50',
  [EXPORT_STATUS.COMPLETED]: '#4CAF50',
  [EXPORT_STATUS.CANCELLED]: '#F44336',
};

// Helper functions
export function isRejectedStatus(status: ExportStatus): boolean {
  return (STATUS_GROUPS.REJECTED as ExportStatus[]).includes(status);
}

export function isPendingStatus(status: ExportStatus): boolean {
  return (STATUS_GROUPS.PENDING as ExportStatus[]).includes(status);
}

export function isApprovedStatus(status: ExportStatus): boolean {
  return (STATUS_GROUPS.APPROVED as ExportStatus[]).includes(status);
}

export function isTerminalStatus(status: ExportStatus): boolean {
  return (STATUS_GROUPS.TERMINAL as ExportStatus[]).includes(status);
}

export function getStatusLabel(status: ExportStatus): string {
  return STATUS_LABELS[status] || status;
}

export function getStatusColor(status: ExportStatus): string {
  return STATUS_COLORS[status] || '#9E9E9E';
}
