-- Migration: Rename ecta_reference_number to lc_number for clarity
-- The ECTA reference number IS the LC (Letter of Credit) number
-- This makes the system more intuitive and aligns with business terminology

-- Rename column in contract_drafts table
ALTER TABLE contract_drafts 
RENAME COLUMN ecta_reference_number TO lc_number;

-- Update index name for consistency
DROP INDEX IF EXISTS idx_contract_drafts_reference;
CREATE INDEX IF NOT EXISTS idx_contract_drafts_lc_number 
ON contract_drafts(lc_number);

-- Rename column in network_submissions table
ALTER TABLE network_submissions 
RENAME COLUMN reference_number TO lc_number;

-- Update index name
DROP INDEX IF EXISTS idx_network_submissions_reference;
CREATE INDEX IF NOT EXISTS idx_network_submissions_lc_number 
ON network_submissions(lc_number);

-- Rename column in contract_notifications table
ALTER TABLE contract_notifications 
RENAME COLUMN ecta_reference_number TO lc_number;

-- Update index name
DROP INDEX IF EXISTS idx_contract_notifications_reference;
CREATE INDEX IF NOT EXISTS idx_contract_notifications_lc_number 
ON contract_notifications(lc_number);

-- Rename column in contract_permissions table
ALTER TABLE contract_permissions 
RENAME COLUMN ecta_reference_number TO lc_number;

-- Update index name
DROP INDEX IF EXISTS idx_contract_permissions_reference;
CREATE INDEX IF NOT EXISTS idx_contract_permissions_lc_number 
ON contract_permissions(lc_number);

-- Update comments
COMMENT ON COLUMN contract_drafts.lc_number IS 'LC Number (Letter of Credit Number) generated by ECTA during sales contract registration (format: SC-YYYY-XXXXX)';
COMMENT ON COLUMN network_submissions.lc_number IS 'LC Number from registered sales contract';
COMMENT ON COLUMN contract_notifications.lc_number IS 'LC Number for contract identification';
COMMENT ON COLUMN contract_permissions.lc_number IS 'LC Number for contract identification';
